CREATE TABLE IF NOT EXISTS `{{ params.project_id }}.{{ params.src_dataset_name }}.ball_by_ball_info` (
  match_id INT64 NOT NULL,
  over_id INT64,
  ball_id INT64,
  innings_no INT64,
  team_batting INT64,
  team_bowling INT64,
  striker_batting_position INT64,
  extra_type STRING,
  runs_scored INT64,
  extra_runs INT64,
  wides INT64,
  legbyes INT64,
  byes INT64,
  noballs INT64,
  penalty INT64,
  bowler_extras INT64,
  out_type STRING,
  caught INT64,
  bowled INT64,
  run_out INT64,
  lbw INT64,
  retired_hurt INT64,
  stumped INT64,
  caught_and_bowled INT64,
  hit_wicket INT64,
  obstructingfeild INT64,
  bowler_wicket INT64,
  match_date DATE,
  season INT64,
  striker INT64,
  non_striker INT64,
  bowler INT64,
  player_out INT64,
  fielders INT64,
  striker_match_sk INT64,
  strikersk INT64,
  nonstriker_match_sk INT64,
  nonstriker_sk INT64,
  fielder_match_sk INT64,
  fielder_sk INT64,
  bowler_match_sk INT64,
  bowler_sk INT64,
  playerout_match_sk INT64,
  battingteam_sk INT64,
  bowlingteam_sk INT64,
  keeper_catch INT64,
  player_out_sk INT64,
  matchdatesk INT64
);


CREATE TABLE IF NOT EXISTS `{{ params.project_id }}.{{ params.src_dataset_name }}.matches_info` (
  match_sk INT64 NOT NULL,
  match_id INT64 NOT NULL,
  team1 STRING,
  team2 STRING,
  match_date DATE,
  season_year INT64,
  venue_name STRING,
  city_name STRING,
  country_name STRING,
  toss_winner STRING,
  match_winner STRING,
  toss_name STRING,
  win_type STRING,
  outcome_type STRING,
  manofmach STRING,
  win_margin INT64,
  country_id INT64
);

CREATE TABLE IF NOT EXISTS `{{ params.project_id }}.{{ params.src_dataset_name }}.player_info` (
  player_sk INT64,
  player_id INT64,
  player_name STRING,
  dob DATE,
  batting_hand STRING,
  bowling_skill STRING,
  country_name STRING
);

CREATE TABLE IF NOT EXISTS `{{ params.project_id }}.{{ params.src_dataset_name }}.player_match_info` (
  player_match_sk INT64 NOT NULL,
  match_id INT64 NOT NULL,
  player_id INT64 NOT NULL,
  player_name STRING,
  dob DATE,
  batting_hand STRING,
  bowling_skill STRING,
  country_name STRING,
  role_desc STRING,
  player_team STRING,
  opposit_team STRING,
  season_year INT64,
  is_manofthematch INT64,
  age_as_on_match INT64,
  isplayers_team_won INT64,
  batting_status STRING,
  bowling_status STRING,
  player_captain STRING,
  opposit_captain STRING,
  player_keeper STRING,
  opposit_keeper STRING
);

CREATE TABLE IF NOT EXISTS `{{ params.project_id }}.{{ params.src_dataset_name }}.teams_info` (
  team_sk INT64 NOT NULL,
  team_id INT64 NOT NULL,
  team_name STRING
);
